name: Test Build on Push
run-name: ${{ github.actor }} is running a build.
on: [push]
jobs:
  build:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v3
        with:
             submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
      - name: Build Deps
        run: msbuild Engine\src\Engine.sln /p:Configuration=Release /p:Platform=x64
      - name: Build something
        run: msbuild Meridian59.sln /p:Configuration=Release
      - name: Upload resources artifact
        uses: actions/upload-artifact@v3
        with:
          name: meridian_resources
          path: "./Resources"
